### ISSUE TITLE
ToT How can I use this library in Android..? 

### ISSUE THREAD

**Issue by mts90** [IZIVIA/ocpp-toolkit#35]
hello sir,

I am a student in University. 

I'm android develop beginner So I don't know use this.

I want to using ocpp 1.6-J core in this library...

plz help me.

**Comment by xhanin** [comment]
Hi,

Unfortunately we don't have the target to me this library usable on
Android, so we haven't made any test for that.

What is your use case ?

**Comment by mts90** [comment]
I have been programming Client part.

So, I want to use to IZIVIA ocpp tookit. but you told me that you didn't any test.

Then I will search other library's..

Thank you for your reply.

**Comment by BurakOgutken** [comment]
@mts90 Hello, have you found a library to use? I'm also looking for one, and I would appreciate your help.
